# User config
author: "Jason Ganub"
tagline: "Home"
description: "I'm Jason, a Tibetan-American lead engineer at Gojek; South East Asia's largest ride-hailing unicorn. Originally born in India, raised in Portland, and now working remotely in Indonesia. I'm an avid traveller, tennis player, and always stirring up an idea to execute."
keywords: "Jason Ganub, Jason, Loden, Ganub, Tibetan American, Tibetan-American"
email: "hi@jasonganub.com"
linkedin: "https://www.linkedin.com/in/jasonganub/"
twitter: "https://twitter.com/jasonganub"
github: "https://github.com/jasonganub"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Google services
google_analytics: G-KFVDP344PX