# User config
author: "Jason Ganub"
tagline: "Home"
description: "I'm Jason, a Tibetan-American born in Dharamsala, India, raised in Portland, OR, USA, and now working remotely in Indonesia. On the hunt for the next idea to execute into a product."
keywords: "Jason Ganub, Jason, Loden, Ganub, Tibetan American, Tibetan-American"
email: "hi@jasonganub.com"
linkedin: "https://www.linkedin.com/in/jasonganub/"
twitter: "https://twitter.com/jasonganub"
github: "https://github.com/jasonganub"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed